"""Controlled owner facts and real storage harness for checker-output custody."""

from __future__ import annotations

from tests.checker_output_admission_helpers import seed_checker_output_relationships

import asyncio
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.adapters.artifacts import create_artifact_store_bootstrap
from app.core.identifiers import new_record_id
from app.modules.checkers.api.output_custody import (
    CheckerOutputArtifactRequest,
    CheckerOutputArtifactResult,
    CheckerOutputBindingRequest,
    CheckerOutputBindingResult,
)
from app.interfaces.artifacts import (
    ArtifactByteRange,
    ArtifactStoreNamespaceClaim,
    ArtifactStoreUnavailableError,
)
from app.modules.actors.api import ServiceIdentity
from app.modules.actors.models import ActorIdentityLink, ActorProfile
from app.modules.artifacts.checker_output_bindings import (
    CheckerOutputBindingService,
)
from app.modules.artifacts.checker_output_custody import CheckerOutputStoredFacts
from app.modules.artifacts.checker_outputs import CheckerArtifactOutputService
from app.modules.artifacts.models import ArtifactBinding
from app.modules.artifacts.preparation import (
    ArtifactPreparationService,
    ArtifactScratchManager,
)
from app.modules.artifacts.schemas import CheckerOutputArtifactAdmissionRequest
from app.modules.artifacts.service import artifact_storage_namespace_spec
from app.modules.checkers.api.output_custody import (
    CheckerOutputReservation,
    CheckerOutputSelector,
    CheckerOutputUnavailable,
)
from app.modules.checkers.models import CheckerRun
from tests.artifact_store_helpers import (
    artifact_admission_limit_settings,
    artifact_preparation_limits,
)
from tests.checker_output_admission_helpers import (
    ControlledCheckerOutputAdmissionAuthority,
    make_checker_output_reservation,
)
from tests.projects.unified_policy_fixtures import create_standalone_unified_policy
from tests.test_artifact_admission import (
    _AllowArtifactAuthority,
    _add_checker_output_actor,
    _settings,
)


def selector_for(reservation: CheckerOutputReservation) -> CheckerOutputSelector:
    """Select the sole controlled output slot under the reservation's current lease."""
    assert len(reservation.slots) == 1
    return CheckerOutputSelector(
        evaluation=reservation.evaluation,
        checker_run_id=reservation.checker_run_id,
        worker_lease_id=reservation.worker_lease_id,
        worker_lease_generation=reservation.worker_lease_generation,
        slot_key=reservation.slots[0].key,
    )


async def byte_stream(*chunks: bytes, observed: list[bytes] | None = None) -> AsyncIterator[bytes]:
    """Yield explicit generated bytes and optionally record source iteration."""
    for chunk in chunks:
        if observed is not None:
            observed.append(chunk)
        yield chunk


@dataclass(slots=True)
class ControlledReservationState:
    """Mutable test control around one immutable owner-issued reservation."""

    reservation: CheckerOutputReservation
    resolved: list[CheckerOutputSelector] = field(default_factory=list)
    revoked: bool = False
    preflights: list[CheckerOutputSelector] = field(default_factory=list)
    prepares: list[CheckerOutputSelector] = field(default_factory=list)
    admissions: list[CheckerOutputArtifactAdmissionRequest] = field(default_factory=list)
    recoveries: list[tuple[CheckerOutputReservation, CheckerOutputStoredFacts]] = field(
        default_factory=list
    )
    bindings: list[tuple[CheckerOutputReservation, CheckerOutputStoredFacts]] = field(
        default_factory=list
    )

    def require_authority(self) -> None:
        """Model one fresh action-authority revocation without product activation."""
        if self.revoked:
            raise CheckerOutputUnavailable("checker_output_test_authority_revoked")


class ControlledReservationPort:
    """Lock a real run, then return controlled detached CHECKERS owner facts."""

    def __init__(self, session: AsyncSession, state: ControlledReservationState) -> None:
        self._session = session
        self._state = state

    async def resolve(self, selector: CheckerOutputSelector) -> CheckerOutputReservation:
        """Fence the selected real run before ART acquires any artifact row lock."""
        checker_run = await self._session.scalar(
            select(CheckerRun)
            .where(CheckerRun.id == str(selector.checker_run_id))
            .with_for_update()
            .execution_options(populate_existing=True)
        )
        if checker_run is None:
            raise CheckerOutputUnavailable("checker_output_reservation_unavailable")
        self._state.resolved.append(selector)
        return self._state.reservation


class ControlledWriteAuthority:
    """Test-only exact action authority plus real fixed-service admission proof."""

    def __init__(
        self,
        session: AsyncSession,
        state: ControlledReservationState,
        actor_id: UUID,
        identity_link_id: UUID,
    ) -> None:
        self._state = state
        self._admission = ControlledCheckerOutputAdmissionAuthority(
            session,
            actor_id,
            identity_link_id,
        )

    async def preflight(self, selector: CheckerOutputSelector) -> None:
        self._state.require_authority()
        self._state.preflights.append(selector)

    async def prepare(self, selector: CheckerOutputSelector) -> None:
        self._state.require_authority()
        self._state.prepares.append(selector)

    async def consume(self, request: CheckerOutputArtifactAdmissionRequest) -> None:
        self._state.require_authority()
        assert request.reservation == self._state.reservation
        await self._admission.consume(request)
        self._state.admissions.append(request)

    async def consume_existing(
        self,
        reservation: CheckerOutputReservation,
        facts: CheckerOutputStoredFacts,
    ) -> None:
        self._state.require_authority()
        assert reservation == self._state.reservation
        self._state.recoveries.append((reservation, facts))

    def discard(self) -> None:
        """The controlled seam retains no prepared capability."""


class ControlledBindingAuthority:
    """Test-only binding authority that records exact verified custody."""

    def __init__(self, state: ControlledReservationState) -> None:
        self._state = state

    async def preflight(self, selector: CheckerOutputSelector) -> None:
        self._state.require_authority()
        self._state.preflights.append(selector)

    async def prepare(self, selector: CheckerOutputSelector) -> None:
        self._state.require_authority()
        self._state.prepares.append(selector)

    async def consume(
        self,
        reservation: CheckerOutputReservation,
        facts: CheckerOutputStoredFacts,
    ) -> None:
        self._state.require_authority()
        assert reservation == self._state.reservation
        self._state.bindings.append((reservation, facts))

    def discard(self) -> None:
        """The controlled seam retains no prepared capability."""


class ObservedStore:
    """Count provider calls and optionally pause one put at the provider boundary."""

    def __init__(self, wrapped: Any) -> None:
        self.wrapped = wrapped
        self.identity = wrapped.identity
        self.puts = 0
        self.opens = 0
        self.put_entered: asyncio.Event | None = None
        self.put_release: asyncio.Event | None = None
        self.lose_put_acknowledgement = False

    async def put(self, source):
        self.puts += 1
        if self.put_entered is not None:
            self.put_entered.set()
        if self.put_release is not None:
            await self.put_release.wait()
        result = await self.wrapped.put(source)
        if self.lose_put_acknowledgement:
            raise ArtifactStoreUnavailableError("controlled lost provider acknowledgement")
        return result

    async def observe_put_result(self, commitment):
        return await self.wrapped.observe_put_result(commitment)

    def open(
        self,
        provider_object_ref: str,
        byte_range: ArtifactByteRange | None = None,
    ):
        self.opens += 1
        return self.wrapped.open(provider_object_ref, byte_range)

    async def head(self, provider_object_ref: str):
        return await self.wrapped.head(provider_object_ref)


@dataclass(slots=True)
class OutputCustodyHarness:
    """One real database/provider path with controlled unavailable owner seams."""

    factory: async_sessionmaker[AsyncSession]
    engine: Any
    bootstrap: Any
    store: ObservedStore
    namespace: Any
    settings: Any
    manager: ArtifactScratchManager
    preparation: ArtifactPreparationService
    service: CheckerArtifactOutputService
    state: ControlledReservationState
    actor_id: UUID
    identity_link_id: UUID
    policy_bundle: Any

    @property
    def selector(self) -> CheckerOutputSelector:
        return selector_for(self.state.reservation)

    def request(
        self,
        *chunks: bytes,
        selector: CheckerOutputSelector | None = None,
        observed: list[bytes] | None = None,
    ) -> CheckerOutputArtifactRequest:
        return CheckerOutputArtifactRequest(
            selector=selector or self.selector,
            byte_source=byte_stream(*chunks, observed=observed),
        )

    def binding_service(self, session: AsyncSession) -> CheckerOutputBindingService:
        return CheckerOutputBindingService(
            session,
            reservations=ControlledReservationPort(session, self.state),
            authority=ControlledBindingAuthority(self.state),
            namespace_fingerprint=self.namespace.namespace_fingerprint,
        )

    async def bind(
        self,
        selector: CheckerOutputSelector,
        stored: CheckerOutputArtifactResult,
    ) -> CheckerOutputBindingResult:
        """Bind one successful stored-output control in its own transaction."""
        assert stored.verification_receipt_id is not None
        async with self.factory() as session:
            async with session.begin():
                return await self.binding_service(session).bind_checker_output(
                    CheckerOutputBindingRequest(
                        selector,
                        stored.put_attempt_id,
                        stored.verification_receipt_id,
                    )
                )

    async def binding_rows(self) -> list[tuple[str, str, str, str, str]]:
        """Snapshot checker-output bindings across both denial-test lineages."""
        async with self.factory() as session:
            rows = await session.execute(
                select(
                    ArtifactBinding.id,
                    ArtifactBinding.content_id,
                    ArtifactBinding.resource_id,
                    ArtifactBinding.put_attempt_id,
                    ArtifactBinding.verification_receipt_id,
                ).where(ArtifactBinding.resource_type == "checker_run").order_by(ArtifactBinding.id)
            )
            return [tuple(row) for row in rows]

    async def seed_reservation(
        self,
        *,
        maximum_bytes: int = 1024,
    ) -> CheckerOutputReservation:
        """Create a second coherent lineage without changing the active test reservation."""
        async with self.factory() as session:
            _, _, checker_run_id = await seed_checker_output_relationships(
                session,
                self.namespace,
                policy_bundle=self.policy_bundle,
            )
            reservation = await make_checker_output_reservation(
                session,
                checker_run_id,
                maximum_bytes=maximum_bytes,
            )
            await session.rollback()
            return reservation


@asynccontextmanager
async def output_custody_harness(
    tmp_path: Path,
    database_url: str,
    *,
    provider: str = "local",
    maximum_bytes: int = 1024,
) -> AsyncIterator[OutputCustodyHarness]:
    """Compose real Local/MinIO storage and controlled exact output authority."""
    engine = create_async_engine(database_url)
    factory = async_sessionmaker(engine, expire_on_commit=False)
    if provider == "minio":
        from tests.test_s3_artifact_store import minio_settings

        settings = minio_settings(private_prefix=f"checker-output/{new_record_id()}").model_copy(
            update={
                **artifact_admission_limit_settings(1024),
                "artifact_scratch_root": tmp_path / "configured-scratch",
                "artifact_scratch_minimum_free_bytes": 0,
            }
        )
    else:
        settings = _settings(tmp_path, maximum_bytes=1024)
    bootstrap = create_artifact_store_bootstrap(settings)
    namespace = artifact_storage_namespace_spec(settings, bootstrap)
    raw_store = bootstrap.initialize_after_namespace_claim(
        ArtifactStoreNamespaceClaim(
            bootstrap.identity,
            bootstrap.namespace_identity,
            namespace.namespace_fingerprint,
        )
    )
    store = ObservedStore(raw_store)
    manager = ArtifactScratchManager(
        root=tmp_path / "output-scratch",
        limits=artifact_preparation_limits(),
    )
    preparation = ArtifactPreparationService(manager)
    try:
        policy_bundle = await create_standalone_unified_policy(factory, namespace)
        async with factory() as session:
            _, _, checker_run_id = await seed_checker_output_relationships(
                session,
                namespace,
                policy_bundle=policy_bundle,
            )
            existing = (
                await session.execute(
                    select(ActorProfile.id, ActorIdentityLink.id)
                    .join(ActorIdentityLink, ActorIdentityLink.actor_profile_id == ActorProfile.id)
                    .where(
                        ActorProfile.service_identity
                        == ServiceIdentity.ARTIFACT_CHECKER_OUTPUT.value
                    )
                )
            ).one_or_none()
            if existing is None:
                actor_id, identity_link_id = new_record_id(), new_record_id()
                _add_checker_output_actor(
                    session,
                    actor_id,
                    identity_link_id,
                    subject=f"checker-output-{actor_id}",
                )
                await session.commit()
            else:
                actor_id, identity_link_id = (UUID(value) for value in existing)
                await session.rollback()
            reservation = await make_checker_output_reservation(
                session,
                checker_run_id,
                maximum_bytes=maximum_bytes,
            )
            await session.rollback()
        state = ControlledReservationState(reservation)
        service = CheckerArtifactOutputService(
            sessions=factory,
            reservations=lambda session: ControlledReservationPort(session, state),
            authority=lambda session: ControlledWriteAuthority(
                session,
                state,
                actor_id,
                identity_link_id,
            ),
            internal_authority=lambda session: _AllowArtifactAuthority(),
            preparation=preparation,
            store=store,
            namespace=namespace,
            settings=settings,
        )
        yield OutputCustodyHarness(
            factory=factory,
            engine=engine,
            bootstrap=bootstrap,
            store=store,
            namespace=namespace,
            settings=settings,
            manager=manager,
            preparation=preparation,
            service=service,
            state=state,
            actor_id=actor_id,
            identity_link_id=identity_link_id,
            policy_bundle=policy_bundle,
        )
    finally:
        manager.close()
        bootstrap.close()
        await engine.dispose()
