"""Dependency-safe public API for the CHECKERS business module."""

from app.modules.checkers.api.external import (
    EXTERNAL_CHECKER_REQUEST_SCHEMA_VERSION,
    EXTERNAL_CHECKER_RESULT_SCHEMA_VERSION,
    POST_SUBMIT_INPUT_SCHEMA_ID,
    PRE_SUBMIT_INPUT_SCHEMA_ID,
    RESULT_SCHEMA_ID,
    ExternalCheckerContractError,
    ExternalCheckerExecutionRequest,
    ExternalCheckerExecutionResult,
    ExternalCheckerFinding,
    ExternalCheckerMaterial,
    ExternalCheckerRegistrationAuthorityFacts,
    ExternalCheckerRegistrationAuthorityPort,
    ExternalCheckerRegistrationAuthorityReceipt,
    ExternalCheckerRegistrationRequest,
    ExternalCheckerRegistryConflict,
    ExternalCheckerRegistryEntry,
    ExternalCheckerRegistryPort,
    ExternalCheckerRegistrySpec,
    ExternalCheckerRegistryUnavailable,
    ExternalCheckerResourceLimits,
    ExternalCheckerSchema,
    PostSubmitExternalCheckerIdentity,
    PreSubmitExternalCheckerIdentity,
    make_external_checker_execution_request,
    make_external_checker_execution_result,
    make_external_checker_registration_request,
)
from app.modules.checkers.api.pre_submit import (
    ALLOWED_PRE_SUBMIT_STORAGE_SCHEMES,
    EffectivePreSubmissionExecutionPlan,
    EffectivePreSubmissionPlanEntry,
    EffectivePreSubmissionPlanError,
    EffectivePreSubmissionPlanLineage,
    EffectivePreSubmissionPlanningPort,
    FrozenJsonObject,
    PreSubmissionExecutionEntryFacts,
    PreSubmissionExecutionFacts,
    PreSubmissionInfrastructureUnavailableError,
    PRE_SUBMISSION_RESULT_METADATA_KEYS,
    SubmissionPacketView,
    validate_pre_submission_execution_facts,
)

__all__ = (
    "ALLOWED_PRE_SUBMIT_STORAGE_SCHEMES",
    "EffectivePreSubmissionExecutionPlan",
    "EffectivePreSubmissionPlanEntry",
    "EffectivePreSubmissionPlanError",
    "EffectivePreSubmissionPlanLineage",
    "EffectivePreSubmissionPlanningPort",
    "FrozenJsonObject",
    "PreSubmissionExecutionEntryFacts",
    "PreSubmissionExecutionFacts",
    "PreSubmissionInfrastructureUnavailableError",
    "PRE_SUBMISSION_RESULT_METADATA_KEYS",
    "SubmissionPacketView",
    "validate_pre_submission_execution_facts",
)

from app.modules.checkers.api.post_submit_catalogue import (
    CompiledPostSubmitPolicy,
    EmptyPostSubmitConfiguration,
    PostSubmitCatalogue,
    PostSubmitDefinition,
    PostSubmitPolicyEntry,
)
from app.modules.checkers.api.post_submit import (
    ExpectedPostSubmitContext,
    ObservedPostSubmitContext,
    PostSubmissionEvaluationContent,
    make_post_submit_request,
    PostSubmissionEvaluationRequest,
    PostSubmissionEvaluationResult,
    PostSubmissionExecutionPort,
    PostSubmissionStructuralInput,
    PostSubmitCurrentResultReference,
    PostSubmitEvidenceEntry,
    PostSubmitManifestEntry,
    PostSubmitMemberResult,
    PostSubmitPolicyInputs,
)

__all__ += (
    "CompiledPostSubmitPolicy", "EmptyPostSubmitConfiguration", "PostSubmitCatalogue",
    "PostSubmitDefinition", "PostSubmitPolicyEntry", "ExpectedPostSubmitContext",
    "ObservedPostSubmitContext", "PostSubmissionEvaluationContent", "make_post_submit_request", "PostSubmissionEvaluationRequest", "PostSubmissionEvaluationResult",
    "PostSubmissionExecutionPort", "PostSubmissionStructuralInput",
    "PostSubmitCurrentResultReference", "PostSubmitEvidenceEntry", "PostSubmitManifestEntry",
    "PostSubmitMemberResult", "PostSubmitPolicyInputs",
)

__all__ += (
    "EXTERNAL_CHECKER_REQUEST_SCHEMA_VERSION",
    "EXTERNAL_CHECKER_RESULT_SCHEMA_VERSION",
    "POST_SUBMIT_INPUT_SCHEMA_ID",
    "PRE_SUBMIT_INPUT_SCHEMA_ID",
    "RESULT_SCHEMA_ID",
    "ExternalCheckerContractError",
    "ExternalCheckerExecutionRequest",
    "ExternalCheckerExecutionResult",
    "ExternalCheckerFinding",
    "ExternalCheckerMaterial",
    "ExternalCheckerRegistrationAuthorityFacts",
    "ExternalCheckerRegistrationAuthorityPort",
    "ExternalCheckerRegistrationAuthorityReceipt",
    "ExternalCheckerRegistrationRequest",
    "ExternalCheckerRegistryConflict",
    "ExternalCheckerRegistryEntry",
    "ExternalCheckerRegistryPort",
    "ExternalCheckerRegistrySpec",
    "ExternalCheckerRegistryUnavailable",
    "ExternalCheckerResourceLimits",
    "ExternalCheckerSchema",
    "PostSubmitExternalCheckerIdentity",
    "PreSubmitExternalCheckerIdentity",
    "make_external_checker_execution_request",
    "make_external_checker_execution_result",
    "make_external_checker_registration_request",
)
