"""Shared pure semantics for Workstream-default pre-submission checks."""

from __future__ import annotations

import re
from collections.abc import Iterable, Sequence
from dataclasses import dataclass


GENERIC_ATTESTATIONS = frozenset({"ok", "done", "yes", "i agree", "confirmed"})
IGNORED_ATTESTATION_TERM_WORDS = frozenset({"a", "an", "and", "for", "of", "the", "exclusion"})
CONFIDENTIALITY_TERMS = ("confidential", "private", "client data", "proprietary")
CREDENTIAL_TERMS = ("credential", "secret", "token", "password", "api key")
SOURCE_PLATFORM_TERMS = (
    "source material",
    "source code",
    "platform artifact",
    "copied artifact",
    "copied platform",
)
LOW_QUALITY_GENERATED_PATTERNS = (
    "todo",
    "placeholder",
    "lorem ipsum",
    "sample output",
    "dummy",
    "generated by chatgpt",
    "as an ai language model",
)


def normalize_policy_token(value: str) -> str:
    """Normalize a policy key or machine term for deterministic comparison."""
    normalized = re.sub(r"[^a-z0-9]+", "_", value.strip().lower())
    return normalized.strip("_")


def attestation_term_is_satisfied(normalized_attestation: str, term: str) -> bool:
    """Return whether an attestation satisfies one machine-readable term key."""
    normalized_term = normalize_policy_token(term)
    if not normalized_term:
        return True
    if normalized_term in normalized_attestation:
        return True
    attestation_words = set(normalized_attestation.split("_"))
    required_words = [
        word
        for word in normalized_term.split("_")
        if word and word not in IGNORED_ATTESTATION_TERM_WORDS
    ]
    return bool(required_words) and all(word in attestation_words for word in required_words)


@dataclass(frozen=True, slots=True)
class AttestationValidationFacts:
    """Canonical attestation facts shared by both pre-submission paths."""

    has_required_length: bool
    has_non_generic_text: bool
    has_confidentiality_term: bool
    has_credential_term: bool
    has_source_or_platform_term: bool
    missing_attestation_terms: tuple[str, ...]


def attestation_validation_facts(
    worker_attestation: str,
    *,
    required_terms: Sequence[str] = (),
) -> AttestationValidationFacts:
    """Return the canonical facts used by both pre-submission execution paths."""
    normalized = " ".join(worker_attestation.strip().lower().split())
    normalized_for_terms = normalize_policy_token(worker_attestation)
    return AttestationValidationFacts(
        has_required_length=len(normalized) >= 40,
        has_non_generic_text=normalized not in GENERIC_ATTESTATIONS,
        has_confidentiality_term=any(term in normalized for term in CONFIDENTIALITY_TERMS),
        has_credential_term=any(term in normalized for term in CREDENTIAL_TERMS),
        has_source_or_platform_term=any(term in normalized for term in SOURCE_PLATFORM_TERMS),
        missing_attestation_terms=tuple(
            term
            for term in required_terms
            if not attestation_term_is_satisfied(normalized_for_terms, term)
        ),
    )


def matched_low_quality_patterns(parts: Iterable[str]) -> tuple[str, ...]:
    """Return deterministic categories without retaining contributor text."""
    haystack = "\n".join(parts).casefold()
    return tuple(
        sorted(pattern for pattern in LOW_QUALITY_GENERATED_PATTERNS if pattern in haystack)
    )
